version: '2.1'

services:
  download_db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  download_ms:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8005"
    container_name: download_ms
    depends_on:
      - download_db
    volumes:
      - SharedFolderContainers:/SharedStorage
    ports:
      - "8005:8005"

volumes:
    SharedFolderContainers:
        external: true
