# Generated by Django 2.2.1 on 2019-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
